name: Default

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Lint, test, and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile --no-progress
      - name: Lint files
        run: yarn lint
      - name: Run build
        env:
          NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_SPACE_ID }}
          NEXT_PUBLIC_CONTENTFUL_API_KEY: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_API_KEY }}
          BUNDLE_ANALYZE: server
        run: yarn build
      - name: Run tests
        run: yarn test --ci --json --coverage --testLocationInResults --outputFile=report.json
